// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: LED

#ifndef UI_INDEX_H
#define UI_INDEX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Index
extern void ui_Index_screen_init(void);
extern void ui_Index_screen_destroy(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_bar_body_box;
extern lv_obj_t * ui_bar;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_car_backdrop;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_power_value_label;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_energy_value_label;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_voltage_value_label;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_current_value_label;
extern lv_obj_t * ui_heading_label;
extern lv_obj_t * ui_subtitle_label;
extern lv_obj_t * ui_start_btn;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_emergency_dialog;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

