// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

lv_obj_t * ui_Index = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_time_label = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_bar_body_box = NULL;
lv_obj_t * ui_bar = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_car_backdrop = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_power_value_label = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_energy_value_label = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_voltage_value_label = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_current_value_label = NULL;
lv_obj_t * ui_heading_label = NULL;
lv_obj_t * ui_subtitle_label = NULL;
lv_obj_t * ui_start_btn = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_emergency_dialog = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Index, lv_color_hex(0x272640), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Index, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Index);
    lv_obj_set_height(ui_Panel1, 36);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x3E3D5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_label = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_time_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time_label, "22:59");
    lv_obj_set_style_text_color(ui_time_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Index);
    lv_obj_set_width(ui_Panel2, 140);
    lv_obj_set_height(ui_Panel2, 75);
    lv_obj_set_x(ui_Panel2, -20);
    lv_obj_set_y(ui_Panel2, -27);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image1, &ui_img_505560643);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -2);
    lv_obj_set_y(ui_Image1, 15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bar_body_box = lv_obj_create(ui_Index);
    lv_obj_set_width(ui_bar_body_box, 230);
    lv_obj_set_height(ui_bar_body_box, 16);
    lv_obj_set_x(ui_bar_body_box, 86);
    lv_obj_set_y(ui_bar_body_box, 177);
    lv_obj_clear_flag(ui_bar_body_box, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bar_body_box, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar_body_box, lv_color_hex(0x006466), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_body_box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bar_body_box, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar = lv_obj_create(ui_bar_body_box);
    lv_obj_set_width(ui_bar, 30);
    lv_obj_set_height(ui_bar, 8);
    lv_obj_set_x(ui_bar, -60);
    lv_obj_set_y(ui_bar, 0);
    lv_obj_set_align(ui_bar, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bar, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Index);
    lv_img_set_src(ui_Image2, &ui_img_303578728);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 30);
    lv_obj_set_y(ui_Image2, 118);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 200);
    lv_obj_set_height(ui_Container6, 200);
    lv_obj_set_x(ui_Container6, 283);
    lv_obj_set_y(ui_Container6, 87);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_car_backdrop = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_car_backdrop, 20);
    lv_obj_set_height(ui_car_backdrop, 20);
    lv_obj_set_align(ui_car_backdrop, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_car_backdrop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_car_backdrop, 900, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_car_backdrop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_car_backdrop, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_car_backdrop, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Container6);
    lv_img_set_src(ui_Image3, &ui_img_hatchback_1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -16);
    lv_obj_set_align(ui_Container2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_flex_grow(ui_Container3, 1);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Power (kW)");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_value_label = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_power_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_power_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_power_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_power_value_label, "2.2");
    lv_obj_set_style_text_color(ui_power_value_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_power_value_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_power_value_label, &ui_font_Arial_Rounded_MT_Bold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_flex_grow(ui_Container1, 1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Energy (kWh)");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energy_value_label = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_energy_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_flex_grow(ui_energy_value_label, 1);
    lv_obj_set_align(ui_energy_value_label, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_energy_value_label, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_energy_value_label, "50.1");
    lv_obj_set_style_text_color(ui_energy_value_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_energy_value_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_energy_value_label, &ui_font_Arial_Rounded_MT_Bold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_flex_grow(ui_Container4, 1);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Voltage (V)");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltage_value_label = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_voltage_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltage_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_voltage_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltage_value_label, "220");
    lv_obj_set_style_text_color(ui_voltage_value_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltage_value_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltage_value_label, &ui_font_Arial_Rounded_MT_Bold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 50);
    lv_obj_set_flex_grow(ui_Container5, 1);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Current (A)");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_current_value_label = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_current_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_current_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_current_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_current_value_label, "6.5");
    lv_obj_set_style_text_color(ui_current_value_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_current_value_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_current_value_label, &ui_font_Arial_Rounded_MT_Bold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heading_label = lv_label_create(ui_Index);
    lv_obj_set_width(ui_heading_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heading_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heading_label, 0);
    lv_obj_set_y(ui_heading_label, 65);
    lv_obj_set_align(ui_heading_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_heading_label, "เชื่อมต่อหัวชาร์จ");
    lv_obj_set_style_text_color(ui_heading_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heading_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_heading_label, &ui_font_Kanit40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_subtitle_label = lv_label_create(ui_Index);
    lv_obj_set_width(ui_subtitle_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_subtitle_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_subtitle_label, 0);
    lv_obj_set_y(ui_subtitle_label, 109);
    lv_obj_set_align(ui_subtitle_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_subtitle_label, "เพื่อเริ่มต้นการชาร์จ");
    lv_obj_add_flag(ui_subtitle_label, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_subtitle_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_subtitle_label, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_subtitle_label, &ui_font_Kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_btn = lv_btn_create(ui_Index);
    lv_obj_set_width(ui_start_btn, 130);
    lv_obj_set_height(ui_start_btn, 44);
    lv_obj_set_x(ui_start_btn, 0);
    lv_obj_set_y(ui_start_btn, -17);
    lv_obj_set_align(ui_start_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_start_btn, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_start_btn, lv_color_hex(0xFFE270), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_start_btn, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_start_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_start_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_start_btn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "เริ่มต้น");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x272640), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_emergency_dialog = lv_obj_create(ui_Index);
    lv_obj_set_width(ui_emergency_dialog, LV_SIZE_CONTENT);   /// 326
    lv_obj_set_height(ui_emergency_dialog, LV_SIZE_CONTENT);    /// 228
    lv_obj_set_align(ui_emergency_dialog, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_emergency_dialog, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_emergency_dialog, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_emergency_dialog, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_emergency_dialog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_emergency_dialog, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_emergency_dialog, lv_color_hex(0xFCFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_emergency_dialog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_emergency_dialog, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_emergency_dialog, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_emergency_dialog, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_emergency_dialog, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_emergency_dialog, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_emergency_dialog);
    lv_img_set_src(ui_Image4, &ui_img_alert_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_emergency_dialog);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "หยุดฉุกเฉิน");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Kanit40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_emergency_dialog);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5,
                      "ปลดสวิตช์หยุดฉุกเฉินเพื่อดำเนินการต่อ");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Index_screen_destroy(void)
{
    if(ui_Index) lv_obj_del(ui_Index);

    // NULL screen variables
    ui_Index = NULL;
    ui_Panel1 = NULL;
    ui_time_label = NULL;
    ui_Panel2 = NULL;
    ui_Image1 = NULL;
    ui_bar_body_box = NULL;
    ui_bar = NULL;
    ui_Image2 = NULL;
    ui_Container6 = NULL;
    ui_car_backdrop = NULL;
    ui_Image3 = NULL;
    ui_Container2 = NULL;
    ui_Container3 = NULL;
    ui_Label2 = NULL;
    ui_power_value_label = NULL;
    ui_Container1 = NULL;
    ui_Label4 = NULL;
    ui_energy_value_label = NULL;
    ui_Container4 = NULL;
    ui_Label6 = NULL;
    ui_voltage_value_label = NULL;
    ui_Container5 = NULL;
    ui_Label8 = NULL;
    ui_current_value_label = NULL;
    ui_heading_label = NULL;
    ui_subtitle_label = NULL;
    ui_start_btn = NULL;
    ui_Label1 = NULL;
    ui_emergency_dialog = NULL;
    ui_Image4 = NULL;
    ui_Label3 = NULL;
    ui_Label5 = NULL;

}
