// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: LED

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_Panel3;
extern void ui_event_back_btn(lv_event_t * e);
extern lv_obj_t * ui_back_btn;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_max_current_dropdown;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

