// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_back_btn = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_max_current_dropdown = NULL;
// event funtions
void ui_event_back_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
    }
}

// build funtions

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_settings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Panel3 = lv_obj_create(ui_settings);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_flex_grow(ui_Panel3, 1);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x202441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_btn = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_back_btn, 130);
    lv_obj_set_height(ui_back_btn, 50);
    lv_obj_set_align(ui_back_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_shadow_width(ui_back_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_back_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_back_btn);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "< ย้อนกลับ");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "กระแสชาร์จสูงสุด");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_max_current_dropdown = lv_dropdown_create(ui_Container8);
    lv_dropdown_set_options(ui_max_current_dropdown, "6A\n12A\n18A\n24A\n30A");
    lv_obj_set_width(ui_max_current_dropdown, 100);
    lv_obj_set_height(ui_max_current_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_max_current_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_max_current_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_max_current_dropdown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_max_current_dropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_max_current_dropdown, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_max_current_dropdown), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_back_btn, ui_event_back_btn, LV_EVENT_ALL, NULL);

}

void ui_settings_screen_destroy(void)
{
    if(ui_settings) lv_obj_del(ui_settings);

    // NULL screen variables
    ui_settings = NULL;
    ui_Panel3 = NULL;
    ui_back_btn = NULL;
    ui_Label7 = NULL;
    ui_Container8 = NULL;
    ui_Label9 = NULL;
    ui_max_current_dropdown = NULL;

}
