// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Index.h"
#include "screens/ui_settings.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * bar_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * circle_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_505560643);    // assets/Artron - 2 1.png
LV_IMG_DECLARE(ui_img_303578728);    // assets/charging-station 1.png
LV_IMG_DECLARE(ui_img_hatchback_1_png);    // assets/hatchback 1.png
LV_IMG_DECLARE(ui_img_alert_png);    // assets/alert.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png

// FONTS
LV_FONT_DECLARE(ui_font_Arial_Rounded_MT_Bold_24);
LV_FONT_DECLARE(ui_font_Kanit20);
LV_FONT_DECLARE(ui_font_Kanit40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
